[workspace]
members = [
    "dactie-peer",
    "dactie-archive",
    "dactie-utils",
    "dactie-authority",
    "ps16",
    "dactie-experiment-anonymity",
    "dactie-experiment-eclipse",
    "thressig"]
resolver = "2"

